# Copyright (c) 2022-2024, PostgreSQL Global Development Group

# ldap_password_func Makefile.exe

# builds a program to obfucate a password using the Playfair algorithm.

PROGRAM = obfuscate
OBJS = pf_encrypt.o playfair.o $(WIN32RES)
PGFILEDESC = "obfuscate a password for use with ldap password hook"

PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
